# Generated by Django 3.2.19 on 2023-05-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jungi_audition',
            name='detail_data',
            field=models.CharField(default=321, max_length=1000),
            preserve_default=False,
        ),
    ]
