# Generated by Django 4.2.1 on 2023-05-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junggi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jungi_audition',
            name='detail_data',
            field=models.TextField(),
        ),
    ]
