# Generated by Django 3.2.19 on 2023-05-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junggi', '0002_alter_jungi_audition_detail_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jungi_audition',
            name='due_date',
            field=models.DateField(),
        ),
    ]
