# Generated by Django 4.2.1 on 2023-05-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangsi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sangsi_audition',
            name='recruitment_field',
            field=models.CharField(max_length=50),
        ),
    ]
