# Generated by Django 4.2.1 on 2023-05-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sangsi_Audition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_agency', models.CharField(max_length=100)),
                ('recruitment_field', models.TextField()),
                ('age_group1', models.IntegerField()),
                ('age_group2', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('detail_data', models.TextField()),
            ],
        ),
    ]
